# Generated by Django 3.2.8 on 2022-03-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220224_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='text',
            new_name='dsc',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='user_id',
        ),
    ]
